// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PandaInfrastructure.ConnectionStrings;

#nullable disable

namespace PandaInfrastructure.Migrations
{
    [DbContext(typeof(PandaDbContext))]
    partial class PandaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PandaDomain.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CityId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("PandaDomain.Entities.Panda", b =>
                {
                    b.Property<int>("PandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("PandaName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PandaId");

                    b.HasIndex("CityId");

                    b.ToTable("Panda");
                });

            modelBuilder.Entity("PandaDomain.Entities.Panda", b =>
                {
                    b.HasOne("PandaDomain.Entities.City", "City")
                        .WithMany("Pandas")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("PandaDomain.Entities.City", b =>
                {
                    b.Navigation("Pandas");
                });
#pragma warning restore 612, 618
        }
    }
}
